export const SOCKET_EVENTS = {
  JOIN: "join",
  NOTE_CREATE: "note:create",
  NOTE_UPDATE: "note:update",
  NOTE_MOVE: "note:move",
  NOTE_DELETE: "note:delete",
  EDGE_CREATE: "edge:create",
  EDGE_DELETE: "edge:delete",
  CLUSTER_CREATE: "cluster:create",
  CLUSTER_UPDATE: "cluster:update",
  CLUSTER_MOVE: "cluster:move",
  CLUSTER_DELETE: "cluster:delete",
  VOTE_ADD: "vote:add",
  VOTE_REMOVE: "vote:remove",
  PHASE_CHANGE: "phase:change",
  ROOM_QUESTION: "room:question",
  SETTINGS_VOTE_BUDGET: "settings:voteBudget",
  TIMER_START: "timer:start",
  TIMER_PAUSE: "timer:pause",
  TIMER_RESET: "timer:reset",
  CURSOR_MOVE: "cursor:move",

  ROOM_STATE: "room:state",
  NOTE_CREATED: "note:created",
  NOTE_UPDATED: "note:updated",
  NOTE_MOVED: "note:moved",
  NOTE_DELETED: "note:deleted",
  EDGE_CREATED: "edge:created",
  EDGE_DELETED: "edge:deleted",
  EDGE_UPDATE: "edge:update",
  EDGE_UPDATED: "edge:updated",
  CLUSTER_CREATED: "cluster:created",
  CLUSTER_UPDATED: "cluster:updated",
  CLUSTER_MOVED: "cluster:moved",
  CLUSTER_DELETED: "cluster:deleted",
  VOTE_ADDED: "vote:added",
  VOTE_REMOVED: "vote:removed",
  SETTINGS_UPDATED: "settings:updated",
  TIMER_UPDATED: "timer:updated",
  QUESTION_UPDATED: "question:updated",
  PRESENCE_JOIN: "presence:join",
  PRESENCE_LEAVE: "presence:leave",
};

export const PHASES = ["lobby", "diverge", "cluster", "converge"];
export const PHASE_LABELS = {
  lobby: "Lobby",
  diverge: "Diverge",
  cluster: "Cluster",
  converge: "Converge",
};